#!/bin/bash

# в файле /etc/passwd каждая строка описывает одного пользователя:
# login : password : UID : GID : GECOS : home : shell
# при указании в регистрационной оболочке :/sbin/nologin пользователю запрещается заходить в систему.
cat /etc/passwd | grep ":/sbin/nologin$" | awk -F ":" '{print $1}'
