#!/bin/bash

if [ -z $1 ]
then
        echo "Отсутствует имя директории"
        exit
fi

if [ -d $1 ]
then
        for c in $1/*
        do
                if [ -p  $c ]
                then
                         fuser -f $c  2>&1 | awk -F":" '/:.{2,}$/{print $1}'
                fi
        done
else
        echo "Дерриктория не обнаружена"
fi
