#!/bin/bash

flag=0

if [ -z $1 ]
then
        echo "Отсутствует имя директории"
        exit
fi

if [ -d $1 ]
then
        for c in $1/*
        do
                if [ -p  $c ]
                then
                        res=$(fuser -f $c  2>&1 | awk -F":" '/:.{2,}$/{print $1}')
                        if [ "$res" ]
                        then
                                echo -e "$res\n"
                                flag=1
                        fi
                fi
        done
else
        echo -e  "Директорию, которую ты ищещь,\n\
        Найти невозможно, но\n\
        Ведь не счесть других."
        exit 1
fi

if [ $flag -eq 0 ]
then
        echo -e "Система так велика,\n\
                 И, должно быть, весьма полезна,\n\
                 Но в ней пайпов нет"
fi