#!/bin/bash

if [ -z $1 ]
then
        echo -e "\
        Хаос царит в системе,\n\
        Всё могло быть в порядке, но\n\
        Отсутствует имя файла."
        exit 1
fi

if ! [ -n "$(ls -l $1 2>/dev/null | awk '/^-/')" ] 
then        
				echo -e  "\
        Файл, который ты ищещь,\n\
        Найти невозможно, но\n\
        Ведь не счесть других."
        exit 1
fi

own=$(ls -n $1 | awk '{print $3}')
echo $own
