#!/bin/bash

# проверка введенных параметров
if [ -z $1 ]
then
        echo -e "\
        Хаос царит в системе,\n\
        Всё могло быть в порядке, но\n\
        Отсутствует имя файла."
        exit 1
fi

# проверка существования файла
if ! [ -n "$(ls -l $1 2>/dev/null | awk '/^-/')" ] 
then        
				echo -e  "\
        Файл, который ты ищещь,\n\
        Найти невозможно, но\n\
        Ведь не счесть других."
        exit 1
fi

# ---------OWNER-----------------------

if [ -n "$(ls -l $1 | awk '/^-.w/')" ]
then
	# own_id -- id владельца файла
	own_id=$(ls -n $1 | awk '{print $3}')
	# own_name -- имя владельца
	own_name=$(getent passwd | grep ".*:.*:$own_id" | awk -F":" '{print $1}')	
fi

# ---------GROUP-----------------------

if [ -n "$(ls -l $1 | awk '/^-....w/')" ]
then
	# group_id -- id группы
	group_id=$(ls -n $1 | awk '{print $4}')
	# group_memp -- пользователи, принадлежащие группе с id = group_id
	group_memb=$(getent passwd | grep ".*:.*:.*:$group_id" | awk -F":" '{print $1}')
fi

# ---------OTHER----------------------

if [ -n "$(ls -l $1 | awk '/^-.......w/')" ]
then
	other=$(getent passwd | awk -F":" '{print $1}')
fi

# --------RESULT----------------------

# результат
echo -e "Пользователи, имеющие права на запись в файл \"$1\":\n"

if [ -n "$own_name" ] 
then 
	echo -e "Владелец:\n$own_name\n"
fi 

if [ -n "$group_memb" ]
then
	echo -e "Пользователи группы:\n$group_memb\n"
fi

if [ -n "$other" ]
then
	echo -e "Остальные пользователи:\n$other\n"
fi
